<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.3.2.min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/live.js'); ?>
<?php $user=$this->data?>
<a href="<?php echo $this->url(array('module'=>'admin',
											'controller'=>'book',
											'action'=>'index',
											'contest'=>$this->contest))?>" ><input type="button" value="Back"></a>
<table style="clear:both;">
<tr>
<td width="300px">
<?php if ($user[0]['image']!=NULL){
	echo '<img width="120" src="'.$this->baseUrl().'/data/'.$user[0]['image'].'">';
	}?>
	<div style="clear:both; text-align: left">
	<h1 class="name">
<?php echo $user[0]['firstname'].'</br>'?>
</h1><h1 class="name">
<?php echo $user[0]['lastname'].'</br>'?>

</h1>
	
	</div>
</td>
<td width="300px" >
<?php if ($user[1]['image']!=NULL){
	echo '<img width="120" style="float:right" src="'.$this->baseUrl().'/data/'.$user[1]['image'].'">';
	}?>
	<div style="clear:both; text-align: right">
	<h1 class="name">
<?php echo '</br>'.$user[1]['firstname'].'</br>'?>
</h1><h1 class="name">
<?php echo $user[1]['lastname'].'</br>'?>
</h1>
	</div>
</td>
</tr>
</table>
<table id="live">
	<tr><td>1*</td><td id="score1"><?php echo $user[0]['score']?></td><td id="score2"><?php echo $user[1]['score']?></td></tr>
	<tr><td>2*</td><td id="liveScore1"><?php echo $user[0]['liveScore']?></td><td id="liveScore2" ><?php echo $user[1]['liveScore']?></td></tr>
	<tr><td>3*</td><td id="lastScore1"><?php echo $user[0]['lastScore']?></td><td id="lastScore2"><?php echo $user[1]['lastScore']?></td></tr>
	</table>
Тайлбар:<br/>
1*-Сетийн харьцаа<br/>
2*-Онооны харьцаа<br/>
3*-Сүүлийн шидэлт<br/>
<?php if (isset($this->form)){?>
<h3>Оноог өөрчлөх:</h3>
<?php
	echo $this->form;
}?>

